### ISSUE TITLE
Alerts are triggered for the opposite side trade even when a position is open

### ISSUE THREAD

**Issue by andrew-rosca** [ConquerTheMarkets/TradingViewIssues#5]
**Steps to replicate:**

A long position is open and the long indicator is positive. The short indicator is still negative. The short indicator now changes to positive.

**Expected outcome:**

No alerts or signals are triggered for the short side because we are already in a long position. 

**Actual outcome:**

An alert/signal is issued for exiting the short position.

**Technical details**

This is happening because the signal logic does not check if we are already in a trade/position. One simple solution might be to only trigger exit signals if a position is open for that side.

**Comment by andrew-rosca** [comment]
This is related to https://github.com/ConquerTheMarkets/TradingViewIssues/issues/4

**Comment by TomKaltz** [comment]
This is fixed in master
